# Generated by Django 4.0.5 on 2022-06-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceapp', '0003_rename_services_servicetypemodel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('no_of_empoyees', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cities', models.ManyToManyField(to='serviceapp.servicecitiesmodel')),
                ('services', models.ManyToManyField(to='serviceapp.servicemodel')),
            ],
        ),
    ]
