# Generated by Django 4.0.5 on 2022-06-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='city',
        ),
        migrations.AddField(
            model_name='servicemodel',
            name='city',
            field=models.ManyToManyField(to='serviceapp.servicecitiesmodel'),
        ),
    ]
