# Generated by Django 4.0.5 on 2022-06-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_remove_servicemodel_city_servicemodel_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetypemodel',
            old_name='services',
            new_name='service',
        ),
    ]
